### ISSUE TITLE
numbered bullets incorrectly rendering as 1, I, or i

### ISSUE THREAD

**Issue by dylang** [GitbookIO/markup-it#27] opened 2016-08-24 19:31 UTC
Hi, I'm noticing rendering issues with the new render engine. Here's one that's pretty significant for our tutorials. 
## Markdown used
- [Rendered by Github](https://gist.github.com/dylang/c9a41b4a32376452c1fb38409d0e2da6)
- [Raw markdown](https://gist.githubusercontent.com/dylang/c9a41b4a32376452c1fb38409d0e2da6/raw/4c88737300460441f62c7762e70fd2b975bbcfa7/nested-numbered-list.md)
## Gitbook 3.1.1

Screenshot using `3.1.1`. This looks correct to us.
![Gitbook 3.1.1](https://cloud.githubusercontent.com/assets/51505/17944824/3ebc1c6e-6a0f-11e6-89d2-67001a797e5a.png)
## Gitbook 3.2.0

Screenshot using `3.2.0`. Notice instead of `1` `2` `3`, it's `1`, `I`, `i`
![Gitbook 3.2.0](https://cloud.githubusercontent.com/assets/51505/17944803/326c7c10-6a0f-11e6-8223-37c2260b0d8e.png)

**Comment by mizunashi-mana** [comment] 2016-09-03 04:11
+1

Unordered List is also:

* [Raw Markdown](https://gist.githubusercontent.com/mizunashi-mana/ab756bfe52b4737203f0d81ae2e404a3/raw/a4ef9ba745268e83e2c549995cdc942deddb63b6/nested-unordered-list.md)
* [Rendered by GitHub](https://gist.github.com/mizunashi-mana/ab756bfe52b4737203f0d81ae2e404a3#file-nested-unordered-list-md)
* Rendered by GitBook:

    ![2016-09-03 13 07 42](https://cloud.githubusercontent.com/assets/11599514/18222606/bfda4bca-71d7-11e6-9cd5-0602c18b1970.png)

**Comment by SamyPesse** [comment] 2016-12-10 00:30
It looks like the issue is fixed in 3.0.1, I've added tests with @mizunashi-mana 's markdown.

GitBook v4 will switch to `markup-it` once we add enough tests for these cases.

**Closed by SamyPesse** 2016-12-10 00:30 UTC
Labels: bug
